/**
 * Generates access codes.
 *
 *   node scripts/gen-codes.mjs                  → 100 codes at level 10
 *   node scripts/gen-codes.mjs 40               → 40 codes at level 10
 *   node scripts/gen-codes.mjs 40 --level=30    → 40 codes at level 30
 *
 * If `db/labels.txt` exists (one label per line), each line becomes a named
 * code and the count becomes the number of lines. A line can carry its own
 * level after a comma, which then applies only to that code:
 *
 *   Ana Souza, 40
 *   Producer X, 20
 *   Festival contact              ← uses the --level default
 *
 * The default is deliberately the lowest level: upgrading a code later is an
 * UPDATE; clawing back material that's already been downloaded isn't.
 *
 * Writes two files, both outside git:
 *   db/seed-codes.sql → for `npm run db:seed`
 *   db/codes.csv      → the human-readable list, for you to distribute
 */
import { randomInt } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const LABELS_FILE = join(root, 'db', 'labels.txt');

// No I, O, 0 or 1: whoever types this from paper or an email won't misread it.
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const CODE_LENGTH = 8;

// Mirrors ACCESS_LEVELS and the `level` values in shared/files.ts. This script
// is .mjs and doesn't import TypeScript; if that changes, change this too.
const LEVELS = [0, 10, 20, 30, 40];
const LEVEL_NAMES = {
  0: 'blocked',
  10: 'One-Pager',
  20: '+ Pitch Deck',
  30: '+ Series Bible',
  40: '+ Season One Full Script',
};
const DEFAULT_LEVEL = 10;

function makeCode() {
  let out = '';
  // randomInt from node:crypto, not Math.random: these codes are the only
  // access barrier to the material.
  for (let i = 0; i < CODE_LENGTH; i += 1) {
    out += ALPHABET[randomInt(ALPHABET.length)];
  }
  return out;
}

function sqlQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function parseLevel(raw, origem) {
  const level = Number(raw);
  if (!LEVELS.includes(level)) {
    console.error(`Invalid level in ${origem}: ${raw}. Use ${LEVELS.join(', ')}.`);
    process.exit(1);
  }
  return level;
}

const args = process.argv.slice(2);
const levelFlag = args.find((a) => a.startsWith('--level='));
const countArg = args.find((a) => !a.startsWith('--'));
const defaultLevel = levelFlag
  ? parseLevel(levelFlag.slice('--level='.length), '--level')
  : DEFAULT_LEVEL;

// "Ana Souza, 40" → label with its own level. Without a comma followed by a
// number, the whole line is the label (and a label with a comma in the
// middle still works).
const labels = existsSync(LABELS_FILE)
  ? readFileSync(LABELS_FILE, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => {
        const m = line.match(/^(.*?)\s*[,;]\s*(\d{1,3})$/);
        return m
          ? { label: m[1].trim(), level: parseLevel(m[2], `db/labels.txt: "${line}"`) }
          : { label: line, level: defaultLevel };
      })
  : null;

const total = labels ? labels.length : Number(countArg ?? 100);
if (!Number.isInteger(total) || total < 1 || total > 5000) {
  console.error('Invalid quantity.');
  process.exit(1);
}

const seen = new Set();
const rows = [];
const createdAt = new Date().toISOString();

while (rows.length < total) {
  const code = makeCode();
  if (seen.has(code)) continue;
  seen.add(code);
  const entry = labels
    ? labels[rows.length]
    : { label: `Guest ${String(rows.length + 1).padStart(3, '0')}`, level: defaultLevel };
  rows.push({ code, label: entry.label, level: entry.level });
}

const sql = [
  '-- Generated by scripts/gen-codes.mjs. DO NOT COMMIT.',
  `-- ${total} codes, ${createdAt}`,
  '',
  ...rows.map(
    (r) =>
      `INSERT OR IGNORE INTO codes (code, label, level, created_at) VALUES (${sqlQuote(
        r.code
      )}, ${sqlQuote(r.label)}, ${r.level}, ${sqlQuote(createdAt)});`
  ),
  '',
].join('\n');

// Hyphen is presentation only; what goes into the database and what the
// Function compares against is always the unseparated form.
const csv = [
  'label,code,formatted_code,level,opens_up_to',
  ...rows.map(
    (r) =>
      `${sqlQuote(r.label).slice(1, -1).replace(/,/g, ' ')},${r.code},${r.code.slice(
        0,
        4
      )}-${r.code.slice(4)},${r.level},${LEVEL_NAMES[r.level]}`
  ),
  '',
].join('\n');

writeFileSync(join(root, 'db', 'seed-codes.sql'), sql, 'utf8');
writeFileSync(join(root, 'db', 'codes.csv'), csv, 'utf8');

const porNivel = LEVELS.map((l) => [l, rows.filter((r) => r.level === l).length]).filter(
  ([, n]) => n > 0
);

console.log(`${total} codes generated.`);
for (const [level, n] of porNivel) {
  console.log(`  level ${String(level).padStart(2)} → ${String(n).padStart(4)} codes  (${LEVEL_NAMES[level]})`);
}
console.log('  db/seed-codes.sql  → npm run db:seed');
console.log('  db/codes.csv       → list to distribute');
console.log(
  labels
    ? 'Labels read from db/labels.txt (use "Name, 30" for a per-line level)'
    : 'Generic labels (create db/labels.txt for named codes)'
);
